name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Release Build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.5"

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Mkdir Bin
        run: mkdir ./bin

      - name: Compile Linux x64
        run: GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o ./bin/garble_linux .

      - name: Compile Linux ARM64
        run: GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -o ./bin/garble_linux-arm64 .

      - name: Compile Windows x64
        run: GOOS=windows GOARCH=amd64 CGO_ENABLED=0 go build -o ./bin/garble_windows.exe .

      - name: Compile macOS x64
        run: GOOS=darwin GOARCH=amd64 CGO_ENABLED=0 go build -o ./bin/garble_macos-amd64 .

      - name: Compile macOS ARM64
        run: GOOS=darwin GOARCH=arm64 CGO_ENABLED=0 go build -o ./bin/garble_macos-arm64 .

      - name: "Publish Release"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: |
            ./bin/*
